AllCops:
  Exclude:
    - 'bin/*'
    - '*.gemspec'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.7.2

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Style/IdenticalConditionalBranches:
  Exclude:
    - 'app/views/**/*'
